---
# https://github.com/google-github-actions/release-please-action#release-types-supported

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master

name: 📦 Create release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 Create release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # to trigger other workflows, pass PAT token instead of GITHUB_TOKEN
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          release-type: node
          package-name: docker-node
          default-branch: master
          changelog-types: |
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "chore", "section": "Miscellaneous", "hidden": false },
              { "type": "style", "section": "Styles", "hidden": true },
              { "type": "revert", "section": "Reverts", "hidden": true },
              { "type": "deps", "section": "Dependencies", "hidden": true },
              { "type": "refactor", "section": "Code Refactoring", "hidden": true },
              { "type": "test", "section": "Tests", "hidden": true },
              { "type": "build", "section": "Build System", "hidden": true },
              { "type": "ci", "section": "Continuous Integration", "hidden": true }
            ]
